apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: gsse
      hasuraService: custom
    name: gsse
    namespace: default
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: gsse
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: gsse
      spec:
        containers:
        - image: gql-schema-stitching:test
          imagePullPolicy: IfNotPresent
          name: gsse
          ports:
          - containerPort: 4000
            protocol: TCP
          resources: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: gsse
      hasuraService: custom
    name: gql-schema-stitching
    namespace: default
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 4000
    selector:
      app: gsse
    type: ClusterIP
kind: List
metadata: {}
